version: ~> 1.0

language: node_js

node_js:
  - 10

sudo: required

services:
    - docker

before_install:
    - docker build -t darthdamo/docker-react -f Dockerfile.dev .

script:
    - docker run darthdamo/docker-react npm run test -- --coverage
